# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(906, 620)
        Dialog.setMaximumSize(QtCore.QSize(906, 620))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame.setStyleSheet("background-color: rgb(78, 110, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(430, 10, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.right_menu = QtWidgets.QFrame(self.frame_2)
        self.right_menu.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.right_menu.setStyleSheet("background-color: rgb(66, 66, 66);")
        self.right_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_menu.setObjectName("right_menu")
        self.label_2 = QtWidgets.QLabel(self.right_menu)
        self.label_2.setGeometry(QtCore.QRect(50, 190, 411, 121))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.right_menu)
        self.label_3.setGeometry(QtCore.QRect(50, 310, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.right_menu)
        self.left_menu = QtWidgets.QFrame(self.frame_2)
        self.left_menu.setMaximumSize(QtCore.QSize(400, 16777215))
        self.left_menu.setStyleSheet("background-color: rgb(116, 169, 255)")
        self.left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu.setObjectName("left_menu")
        self.pushButton = QtWidgets.QPushButton(self.left_menu)
        self.pushButton.setGeometry(QtCore.QRect(290, 520, 93, 28))
        self.pushButton.setStyleSheet("background-color: rgb(255, 74, 116);")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.left_menu)
        self.lineEdit.setGeometry(QtCore.QRect(60, 200, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.left_menu)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 250, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_18 = QtWidgets.QPushButton(self.left_menu)
        self.pushButton_18.setGeometry(QtCore.QRect(170, 310, 93, 28))
        self.pushButton_18.setStyleSheet("background-color: rgb(78, 110, 255);\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout.addWidget(self.left_menu)
        self.verticalLayout.addWidget(self.frame_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "LOGIN"))
        self.label_2.setText(_translate("Dialog", "Concessionária \n"
"DriveNation"))
        self.label_3.setText(_translate("Dialog", "Você mais veloz"))
        self.pushButton.setText(_translate("Dialog", "sair"))
        self.lineEdit.setText(_translate("Dialog", "GMAIL"))
        self.lineEdit_2.setText(_translate("Dialog", "SENHA"))
        self.pushButton_18.setText(_translate("Dialog", "ENTRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
