# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget
from PyQt5.QtCore import Qt
import sys
import files_rc
import conversor

#----------------------------------------------------------------

class Example(QWidget):

        def __init__(self):
                super().__init__()
                self.initUI()

        def initUI(self):
                Dialog = QtWidgets.QDialog()
                self.setupUi(Dialog)
                self.comboBox.currentIndexChanged.connect(lambda: self.start())
                self.comboBox_2.currentIndexChanged.connect(lambda: self.start())
                self.lineEdit.textChanged.connect(lambda: self.start())
#                self.lineEdit.textEdited()
#                self.lineEdit.changeEvent(self.lineEdit_2.setText((conversor.iniciar(self.comboBox, self.comboBox_2, self.lineEdit))))
                Dialog.show()   
                Dialog.setWindowTitle('Conversor Numerico')
                sys.exit(app.exec_())               

#----------------------------------------------------------------

        def textChanged(self):
            print('a')

#----------------------------------------------------------------


        def setupUi(self, Dialog):
            Dialog.setObjectName("Dialog")
            Dialog.resize(900, 550)
            Dialog.setMinimumSize(QtCore.QSize(900, 550))
            self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
            self.verticalLayout.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout.setSpacing(0)
            self.verticalLayout.setObjectName("verticalLayout")
            self.top_conversor = QtWidgets.QFrame(Dialog)
            self.top_conversor.setMaximumSize(QtCore.QSize(16777215, 120))
            self.top_conversor.setStyleSheet("background-color:rgb(0, 0, 127)\n"
    "")
            self.top_conversor.setFrameShape(QtWidgets.QFrame.NoFrame)
            self.top_conversor.setFrameShadow(QtWidgets.QFrame.Raised)
            self.top_conversor.setObjectName("top_conversor")
            self.photo_frme = QtWidgets.QFrame(self.top_conversor)
            self.photo_frme.setGeometry(QtCore.QRect(170, 29, 651, 91))
            self.photo_frme.setStyleSheet("background-image: url(:/Title/conversor_foto.png);")
            self.photo_frme.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.photo_frme.setFrameShadow(QtWidgets.QFrame.Raised)
            self.photo_frme.setObjectName("photo_frme")
            self.verticalLayout.addWidget(self.top_conversor)
            self.content = QtWidgets.QFrame(Dialog)
            self.content.setStyleSheet("background-color:rgb(15, 15, 15)")
            self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.content.setFrameShadow(QtWidgets.QFrame.Raised)
            self.content.setObjectName("content")
            self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
            self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout.setSpacing(0)
            self.horizontalLayout.setObjectName("horizontalLayout")
            self.unidade_1 = QtWidgets.QFrame(self.content)
            self.unidade_1.setMinimumSize(QtCore.QSize(0, 0))
            self.unidade_1.setStyleSheet("background-color: rgb(35, 35, 35);")
            self.unidade_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.unidade_1.setFrameShadow(QtWidgets.QFrame.Raised)
            self.unidade_1.setObjectName("unidade_1")
            self.frame = QtWidgets.QFrame(self.unidade_1)
            self.frame.setGeometry(QtCore.QRect(10, 80, 141, 61))
            self.frame.setStyleSheet("background-image: url(:/newPrefix/Untitled.png);")
            self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
            self.frame.setObjectName("frame")
            self.comboBox = QtWidgets.QComboBox(self.unidade_1)
            self.comboBox.setGeometry(QtCore.QRect(50, 150, 311, 51))
            self.comboBox.setStyleSheet("background-color: rgb(118, 118, 118);\n"
    "font: 13pt \"MS Shell Dlg 2\";\n"
    "color: rgb(255, 255, 255);")
            self.comboBox.setObjectName("comboBox")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.comboBox.addItem("")
            self.frame_3 = QtWidgets.QFrame(self.unidade_1)
            self.frame_3.setGeometry(QtCore.QRect(10, 240, 111, 51))
            self.frame_3.setStyleSheet("background-image: url(:/Title/Untitled (3).png);")
            self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
            self.frame_3.setObjectName("frame_3")
            self.lineEdit = QtWidgets.QLineEdit(self.unidade_1)
            self.lineEdit.setGeometry(QtCore.QRect(50, 290, 311, 51))
            self.lineEdit.setStyleSheet("background-color: rgb(118, 118, 118);\n"
    "font: 13pt \"MS Shell Dlg 2\";\n"
    "color: rgb(255, 255, 255);")
            self.lineEdit.setText("")
            self.lineEdit.setObjectName("lineEdit")
            self.horizontalLayout.addWidget(self.unidade_1)
            self.unidade_2 = QtWidgets.QFrame(self.content)
            self.unidade_2.setStyleSheet("background-color: rgb(60, 60, 60);")
            self.unidade_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.unidade_2.setFrameShadow(QtWidgets.QFrame.Raised)
            self.unidade_2.setObjectName("unidade_2")
            self.frame_2 = QtWidgets.QFrame(self.unidade_2)
            self.frame_2.setGeometry(QtCore.QRect(0, 80, 131, 61))
            self.frame_2.setStyleSheet("background-image: url(:/Title/Untitled (2).png);")
            self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
            self.frame_2.setObjectName("frame_2")
            self.comboBox_2 = QtWidgets.QComboBox(self.unidade_2)
            self.comboBox_2.setGeometry(QtCore.QRect(30, 150, 311, 51))
            self.comboBox_2.setStyleSheet("background-color: rgb(118, 118, 118);\n"
    "font: 13pt \"MS Shell Dlg 2\";\n"
    "color: rgb(255, 255, 255);")
            self.comboBox_2.setObjectName("comboBox_2")
            self.comboBox_2.addItem("")
            self.comboBox_2.addItem("")
            self.comboBox_2.addItem("")
            self.frame_4 = QtWidgets.QFrame(self.unidade_2)
            self.frame_4.setGeometry(QtCore.QRect(20, 240, 120, 51))
            self.frame_4.setStyleSheet("background-image: url(:/Title/Untitled (1).png);")
            self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
            self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
            self.frame_4.setObjectName("frame_4")
            self.lineEdit_2 = QtWidgets.QLineEdit(self.unidade_2)
            self.lineEdit_2.setGeometry(QtCore.QRect(30, 290, 311, 51))
            self.lineEdit_2.setStyleSheet("background-color: rgb(118, 118, 118);\n"
    "font: 13pt \"MS Shell Dlg 2\";\n"
    "color: rgb(255, 255, 255);")
            self.lineEdit_2.setText("")
            self.lineEdit_2.setObjectName("lineEdit_2")
            self.horizontalLayout.addWidget(self.unidade_2)
            self.verticalLayout.addWidget(self.content)

            self.retranslateUi(Dialog)
            QtCore.QMetaObject.connectSlotsByName(Dialog)

        def retranslateUi(self, Dialog):
            _translate = QtCore.QCoreApplication.translate
            Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
            self.comboBox.setItemText(0, _translate("Dialog", "Decimal"))
            self.comboBox.setItemText(1, _translate("Dialog", "Binario"))
            self.comboBox.setItemText(2, _translate("Dialog", "Hexadecimal"))
            self.comboBox_2.setItemText(0, _translate("Dialog", "Decimal"))
            self.comboBox_2.setItemText(1, _translate("Dialog", "Binario"))
            self.comboBox_2.setItemText(2, _translate("Dialog", "Hexadecimal"))

        def start(self):
                sistemaNumericoEntrada = self.comboBox.currentText()
                sistemaNumericoSaida = self.comboBox_2.currentText()
                numeroDeEntrada = self.lineEdit.text()
                numeroDeSaida = self.lineEdit_2.text()
                self.process(sistemaNumericoEntrada, sistemaNumericoSaida, numeroDeEntrada)
            
        def process(self, sistemaNumericoEntrada, sistemaNumericoSaida, numeroDeEntrada):
                self.lineEdit_2.setText((conversor.iniciar(sistemaNumericoEntrada, sistemaNumericoSaida, numeroDeEntrada)))
#----------------------------------------------------------------

if __name__ == "__main__":
    app = QApplication(sys.argv)
    ex = Example()